<%if(testEnv) {%>
<script src="<%=staticPath%>/js/storeIncLoad.js"></script>
<script src="<%=staticPath%>/js/core.js"></script>
<script type="text/javascript">
	var g_config = {
            jsmap:{
                'jqmobi': '/mod/jqmobi.js',
				'iScroll':'/mod/iScroll.js',
				'loadMod':'/mod/loading.js',
				'loginMod':'/mod/loginModule.js',
				'loadUtil':'/mod/loadUtil.js',
				'msgMod':'/mod/msgMod.js',
				'shareMod':'/mod/shareModule.js',
				'tipsModule':'/mod/tipsModule.js',
				'app_comment':'/mod/app_comment.js',
				'subMrg':'/mod/subMrg.js',
				'autocomplete':'/mod/autocomplete.js',
				'pm': '/mod/pm.js',
				'init': '/init.js',
				'imgque':'/mod/imgque.js',
				'swipe':'/mod/swipe.js',
				'swipe1':'/mod/swipe_1.js',
				'util':'/mod/util.js',
				'base64':'/mod/base64.js',
				'popDialog':'/mod/popDialog.js',
				'conf':'/conf.js',
				'editmvlist':'/mod/editmvlist.js',
				'iScroll':'/mod/iscroll-lite.js',
				'subview':'/mod/subview.js',
				'handleMore':'/mod/handleMore.js',
				'lightapp':'/mod/lightapp.js',
				'app_footer':'/mod/app_footer.js',
				'toolbar': '/mod/toolbar.js',
				'owly': '/mod/owly.js',
				'subpages.mvlist_list':'/pages/subpages/mvlist_list.js',
				'subpages.mvlist_cmt':'/pages/subpages/mvlist_cmt.js',
				'subpages.mvlist_relate':'/pages/subpages/mvlist_relate.js',
				'subpages.rank_mv':'/pages/subpages/rank_mv.js',
				'subpages.rank_mvlist':'/pages/subpages/rank_mvlist.js',
				'subpages.rank_supper':'/pages/subpages/rank_supper.js',
				'page.home':'/pages/home.js',
				'page.search':'/pages/search.js',
				'page.search_result':'/pages/search_result.js',
				'page.mvinfo':'/pages/mvinfo.js',
				'page.lcomment':'/pages/lcomment.js',
				'page.lcommentinfo':'/pages/lcommentinfo.js',
				'page.comment':'/pages/comment.js',
				'page.bigimg':'/pages/bigimg.js',
				'page.imglist':'/pages/imglist.js',
				'page.video':'/pages/video.js',
				'page.mvlistinfo':'/pages/mvlistinfo.js',
				'page.share':'/pages/share.js',
				'page.mvlistsort':'/pages/mvlist_sort.js',
				'page.addmvlist':'/pages/addmvlist.js',
				'page.createmvlist':'/pages/createmvlist.js',
				'page.mvlistedit':'/pages/mvlistedit.js',
				'page.rank':'/pages/rank.js',
				'page.mvlistall':'/pages/mvlistall.js',
				'page.ucenter':'/pages/ucenter.js',
				'page.managelist':'/pages/managelist.js',
				'page.guide':'/pages/guide.js',
				'page.iwant':'/pages/iwant.js',
				'page.unfound': '/pages/404.js',
				'page.gfinner':'/pages/gfinner.js'
            },
            storeInc:{},
            staticPath: '<%=request.getContextPath()%>/movie/frontend2/js',
            testEnv: true
        };
  </script>
<%} else{%>
<script src="http://3gimg.qq.com/wap30/info/storeIncLoad-core.js"></script>
<script type="text/javascript" id="file_config">
var g_config = {
            jsmap:{
                'jqmobi': '/imovie.js?017',
				'loadMod':'/imovie.js',
				'loginMod':'/imovie.js',
				'loadUtil':'/imovie.js',
				'msgMod':'/imovie.js',
				'shareMod':'/pages/share.js?005',
				'tipsModule':'/imovie.js',
				'app_comment':'/imovie.js',
				'subMrg':'/imovie.js',
				'autocomplete':'/imovie.js',
				'pm': '/imovie.js',
				'init': '/imovie.js',
				'imgque':'/imovie.js',
				'swipe':'/pages/home.js?014',
				'swipe1':'/pages/bigimg.js?005',
				'util':'/imovie.js',
				'base64':'/pages/share.js',
				'popDialog':'/pages/share.js',
				'conf':'/imovie.js',
				'editmvlist':'/pages/mvlistinfo.js?011',
				'iScroll':'/pages/mvlistall.js?009',
				'subview':'/imovie.js',
				'handleMore':'/imovie.js',
				'toolbar': '/plugin/toolbar.js',
				'owly': '/imovie.js',
				'lightapp':'/pages/home.js',
				'subpages.mvlist_list':'/pages/mvlistinfo.js',
				'subpages.mvlist_cmt':'/pages/mvlistinfo.js',
				'subpages.mvlist_relate':'/pages/mvlistinfo.js',
				'subpages.rank_mv':'/pages/rank.js?008',
				'subpages.rank_mvlist':'/pages/rank.js',
				'subpages.rank_supper':'/pages/rank.js',
				'page.home':'/pages/home.js',
				'page.search':'/pages/search.js?005',
				'page.search_result':'/pages/search_result.js?006',
				'page.mvinfo':'/pages/mvinfo.js?012',
				'page.lcomment':'/pages/lcomment.js',
				'page.lcommentinfo':'/pages/lcommentinfo.js?006',
				'page.comment':'/pages/comment.js?006',
				'page.bigimg':'/pages/bigimg.js?005',
				'page.imglist':'/pages/imglist.js?006',
				'page.video':'/pages/video.js?007',
				'page.mvlistinfo':'/pages/mvlistinfo.js',
				'page.share':'/pages/share.js',
				'page.mvlistsort':'/pages/mvlist_sort.js?006',
				'page.addmvlist':'/pages/addmvlist.js?004',
				'page.createmvlist':'/pages/createmvlist.js?005',
				'page.mvlistedit':'/pages/mvlistedit.js?004',
				'page.rank':'/pages/rank.js',
				'page.mvlistall':'/pages/mvlistall.js',
				'page.ucenter':'/pages/ucenter.js?003',
				'page.managelist':'/pages/managelist.js?009',
				'page.guide':'/pages/guide.js?002',
				'page.iwant':'/pages/iwant.js?007',
				'page.unfound': '/pages/404.js',
				'page.gfinner':'/pages/gfinner.js'
            },
           storeInc:{
                'store': true,
                'inc': true,
                'debug': false
            },
            testEnv: false,
            // staticPath: '/g/movie/frontend2/release/new',
            staticPath: '/wap30/infoapp/touch/movie2/js',
            buildType: 'file'
        };
        </script>
<%}%>